### ISSUE TITLE
com.apple.applicationaccess.plist

### ISSUE THREAD

**Issue by TipSpy** [sincerelyjoshin/macOS-property-lists#23]
`<key>allowSpotlightInternetResults</key>` is currently set to `<false/>`, should be `<true/>`.

**Comment by sincerelyjoshin** [comment]
I will look into why I have it set to false. Sounds like something I wouldn't manage unless I had to.

**Comment by sincerelyjoshin** [comment]
Disabling internet results from Spotlight was actually the functionality I was wanting.
